// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/url/url.proto

package urlpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,4,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"`
	IsActive             bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt            *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastCheckedAt        *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=last_checked_at,json=lastCheckedAt,proto3" json:"last_checked_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_proto_url_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *URL) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *URL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *URL) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

func (x *URL) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *URL) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *URL) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *URL) GetLastCheckedAt() *timestamp.Timestamp {
	if x != nil {
		return x.LastCheckedAt
	}
	return nil
}

type CreateURLRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,3,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateURLRequest) Reset() {
	*x = CreateURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRequest) ProtoMessage() {}

func (x *CreateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRequest.ProtoReflect.Descriptor instead.
func (*CreateURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{1}
}

func (x *CreateURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateURLRequest) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListURLsRequest) Reset() {
	*x = ListURLsRequest{}
	mi := &file_proto_url_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsRequest) ProtoMessage() {}

func (x *ListURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsRequest.ProtoReflect.Descriptor instead.
func (*ListURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{3}
}

func (x *ListURLsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListURLsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListURLsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URL                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListURLsResponse) Reset() {
	*x = ListURLsResponse{}
	mi := &file_proto_url_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsResponse) ProtoMessage() {}

func (x *ListURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsResponse.ProtoReflect.Descriptor instead.
func (*ListURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{4}
}

func (x *ListURLsResponse) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ListURLsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateURLRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	CheckIntervalSeconds int32                  `protobuf:"varint,4,opt,name=check_interval_seconds,json=checkIntervalSeconds,proto3" json:"check_interval_seconds,omitempty"`
	IsActive             bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateURLRequest) Reset() {
	*x = UpdateURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateURLRequest) ProtoMessage() {}

func (x *UpdateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateURLRequest.ProtoReflect.Descriptor instead.
func (*UpdateURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateURLRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpdateURLRequest) GetCheckIntervalSeconds() int32 {
	if x != nil {
		return x.CheckIntervalSeconds
	}
	return 0
}

func (x *UpdateURLRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLRequest) Reset() {
	*x = DeleteURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLRequest) ProtoMessage() {}

func (x *DeleteURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteURLRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteURLRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLResponse) Reset() {
	*x = DeleteURLResponse{}
	mi := &file_proto_url_url_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLResponse) ProtoMessage() {}

func (x *DeleteURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListActiveURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveURLsRequest) Reset() {
	*x = ListActiveURLsRequest{}
	mi := &file_proto_url_url_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveURLsRequest) ProtoMessage() {}

func (x *ListActiveURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveURLsRequest.ProtoReflect.Descriptor instead.
func (*ListActiveURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{8}
}

func (x *ListActiveURLsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_proto_url_url_proto protoreflect.FileDescriptor

const file_proto_url_url_proto_rawDesc = "" +
	"\n" +
	"\x13proto/url/url.proto\x12\x03url\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x02\n" +
	"\x03URL\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x124\n" +
	"\x16check_interval_seconds\x18\x04 \x01(\x05R\x14checkIntervalSeconds\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\x0flast_checked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlastCheckedAt\"s\n" +
	"\x10CreateURLRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x124\n" +
	"\x16check_interval_seconds\x18\x03 \x01(\x05R\x14checkIntervalSeconds\"8\n" +
	"\rGetURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"X\n" +
	"\x0fListURLsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"F\n" +
	"\x10ListURLsResponse\x12\x1c\n" +
	"\x04urls\x18\x01 \x03(\v2\b.url.URLR\x04urls\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa0\x01\n" +
	"\x10UpdateURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x124\n" +
	"\x16check_interval_seconds\x18\x04 \x01(\x05R\x14checkIntervalSeconds\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\";\n" +
	"\x10DeleteURLRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"-\n" +
	"\x11DeleteURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x15ListActiveURLsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit2\xca\x02\n" +
	"\n" +
	"URLService\x12,\n" +
	"\tCreateURL\x12\x15.url.CreateURLRequest\x1a\b.url.URL\x12&\n" +
	"\x06GetURL\x12\x12.url.GetURLRequest\x1a\b.url.URL\x127\n" +
	"\bListURLs\x12\x14.url.ListURLsRequest\x1a\x15.url.ListURLsResponse\x12,\n" +
	"\tUpdateURL\x12\x15.url.UpdateURLRequest\x1a\b.url.URL\x12:\n" +
	"\tDeleteURL\x12\x15.url.DeleteURLRequest\x1a\x16.url.DeleteURLResponse\x12C\n" +
	"\x0eListActiveURLs\x12\x1a.url.ListActiveURLsRequest\x1a\x15.url.ListURLsResponseB/Z-github.com/shakir/url-monitor/proto/url;urlpbb\x06proto3"

var (
	file_proto_url_url_proto_rawDescOnce sync.Once
	file_proto_url_url_proto_rawDescData []byte
)

func file_proto_url_url_proto_rawDescGZIP() []byte {
	file_proto_url_url_proto_rawDescOnce.Do(func() {
		file_proto_url_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_url_url_proto_rawDesc), len(file_proto_url_url_proto_rawDesc)))
	})
	return file_proto_url_url_proto_rawDescData
}

var file_proto_url_url_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_url_url_proto_goTypes = []any{
	(*URL)(nil),                   // 0: url.URL
	(*CreateURLRequest)(nil),      // 1: url.CreateURLRequest
	(*GetURLRequest)(nil),         // 2: url.GetURLRequest
	(*ListURLsRequest)(nil),       // 3: url.ListURLsRequest
	(*ListURLsResponse)(nil),      // 4: url.ListURLsResponse
	(*UpdateURLRequest)(nil),      // 5: url.UpdateURLRequest
	(*DeleteURLRequest)(nil),      // 6: url.DeleteURLRequest
	(*DeleteURLResponse)(nil),     // 7: url.DeleteURLResponse
	(*ListActiveURLsRequest)(nil), // 8: url.ListActiveURLsRequest
	(*timestamp.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_url_url_proto_depIdxs = []int32{
	9,  // 0: url.URL.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: url.URL.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: url.URL.last_checked_at:type_name -> google.protobuf.Timestamp
	0,  // 3: url.ListURLsResponse.urls:type_name -> url.URL
	1,  // 4: url.URLService.CreateURL:input_type -> url.CreateURLRequest
	2,  // 5: url.URLService.GetURL:input_type -> url.GetURLRequest
	3,  // 6: url.URLService.ListURLs:input_type -> url.ListURLsRequest
	5,  // 7: url.URLService.UpdateURL:input_type -> url.UpdateURLRequest
	6,  // 8: url.URLService.DeleteURL:input_type -> url.DeleteURLRequest
	8,  // 9: url.URLService.ListActiveURLs:input_type -> url.ListActiveURLsRequest
	0,  // 10: url.URLService.CreateURL:output_type -> url.URL
	0,  // 11: url.URLService.GetURL:output_type -> url.URL
	4,  // 12: url.URLService.ListURLs:output_type -> url.ListURLsResponse
	0,  // 13: url.URLService.UpdateURL:output_type -> url.URL
	7,  // 14: url.URLService.DeleteURL:output_type -> url.DeleteURLResponse
	4,  // 15: url.URLService.ListActiveURLs:output_type -> url.ListURLsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_url_url_proto_init() }
func file_proto_url_url_proto_init() {
	if File_proto_url_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_url_url_proto_rawDesc), len(file_proto_url_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_url_url_proto_goTypes,
		DependencyIndexes: file_proto_url_url_proto_depIdxs,
		MessageInfos:      file_proto_url_url_proto_msgTypes,
	}.Build()
	File_proto_url_url_proto = out.File
	file_proto_url_url_proto_goTypes = nil
	file_proto_url_url_proto_depIdxs = nil
}
