// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/analytics/analytics.proto

package analyticspb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetURLStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UrlId         int64                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	From          *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLStatsRequest) Reset() {
	*x = GetURLStatsRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLStatsRequest) ProtoMessage() {}

func (x *GetURLStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLStatsRequest.ProtoReflect.Descriptor instead.
func (*GetURLStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetURLStatsRequest) GetUrlId() int64 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

func (x *GetURLStatsRequest) GetFrom() *timestamp.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetURLStatsRequest) GetTo() *timestamp.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

type URLStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UrlId             int64                  `protobuf:"varint,1,opt,name=url_id,json=urlId,proto3" json:"url_id,omitempty"`
	TotalChecks       int64                  `protobuf:"varint,2,opt,name=total_checks,json=totalChecks,proto3" json:"total_checks,omitempty"`
	SuccessfulChecks  int64                  `protobuf:"varint,3,opt,name=successful_checks,json=successfulChecks,proto3" json:"successful_checks,omitempty"`
	FailedChecks      int64                  `protobuf:"varint,4,opt,name=failed_checks,json=failedChecks,proto3" json:"failed_checks,omitempty"`
	UptimePercentage  float64                `protobuf:"fixed64,5,opt,name=uptime_percentage,json=uptimePercentage,proto3" json:"uptime_percentage,omitempty"`
	AvgResponseTimeMs float64                `protobuf:"fixed64,6,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	LastStatusCode    int32                  `protobuf:"varint,7,opt,name=last_status_code,json=lastStatusCode,proto3" json:"last_status_code,omitempty"`
	IsCurrentlyUp     bool                   `protobuf:"varint,8,opt,name=is_currently_up,json=isCurrentlyUp,proto3" json:"is_currently_up,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *URLStats) Reset() {
	*x = URLStats{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLStats) ProtoMessage() {}

func (x *URLStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLStats.ProtoReflect.Descriptor instead.
func (*URLStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *URLStats) GetUrlId() int64 {
	if x != nil {
		return x.UrlId
	}
	return 0
}

func (x *URLStats) GetTotalChecks() int64 {
	if x != nil {
		return x.TotalChecks
	}
	return 0
}

func (x *URLStats) GetSuccessfulChecks() int64 {
	if x != nil {
		return x.SuccessfulChecks
	}
	return 0
}

func (x *URLStats) GetFailedChecks() int64 {
	if x != nil {
		return x.FailedChecks
	}
	return 0
}

func (x *URLStats) GetUptimePercentage() float64 {
	if x != nil {
		return x.UptimePercentage
	}
	return 0
}

func (x *URLStats) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *URLStats) GetLastStatusCode() int32 {
	if x != nil {
		return x.LastStatusCode
	}
	return 0
}

func (x *URLStats) GetIsCurrentlyUp() bool {
	if x != nil {
		return x.IsCurrentlyUp
	}
	return false
}

type GetUserDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDashboardRequest) Reset() {
	*x = GetUserDashboardRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDashboardRequest) ProtoMessage() {}

func (x *GetUserDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetUserDashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserDashboardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserDashboard struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalUrls         int32                  `protobuf:"varint,2,opt,name=total_urls,json=totalUrls,proto3" json:"total_urls,omitempty"`
	ActiveUrls        int32                  `protobuf:"varint,3,opt,name=active_urls,json=activeUrls,proto3" json:"active_urls,omitempty"`
	UrlsCurrentlyUp   int32                  `protobuf:"varint,4,opt,name=urls_currently_up,json=urlsCurrentlyUp,proto3" json:"urls_currently_up,omitempty"`
	UrlsCurrentlyDown int32                  `protobuf:"varint,5,opt,name=urls_currently_down,json=urlsCurrentlyDown,proto3" json:"urls_currently_down,omitempty"`
	TopUrls           []*URLStats            `protobuf:"bytes,6,rep,name=top_urls,json=topUrls,proto3" json:"top_urls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserDashboard) Reset() {
	*x = UserDashboard{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDashboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDashboard) ProtoMessage() {}

func (x *UserDashboard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDashboard.ProtoReflect.Descriptor instead.
func (*UserDashboard) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *UserDashboard) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDashboard) GetTotalUrls() int32 {
	if x != nil {
		return x.TotalUrls
	}
	return 0
}

func (x *UserDashboard) GetActiveUrls() int32 {
	if x != nil {
		return x.ActiveUrls
	}
	return 0
}

func (x *UserDashboard) GetUrlsCurrentlyUp() int32 {
	if x != nil {
		return x.UrlsCurrentlyUp
	}
	return 0
}

func (x *UserDashboard) GetUrlsCurrentlyDown() int32 {
	if x != nil {
		return x.UrlsCurrentlyDown
	}
	return 0
}

func (x *UserDashboard) GetTopUrls() []*URLStats {
	if x != nil {
		return x.TopUrls
	}
	return nil
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x12GetURLStatsRequest\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x03R\x05urlId\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\"\xc6\x02\n" +
	"\bURLStats\x12\x15\n" +
	"\x06url_id\x18\x01 \x01(\x03R\x05urlId\x12!\n" +
	"\ftotal_checks\x18\x02 \x01(\x03R\vtotalChecks\x12+\n" +
	"\x11successful_checks\x18\x03 \x01(\x03R\x10successfulChecks\x12#\n" +
	"\rfailed_checks\x18\x04 \x01(\x03R\ffailedChecks\x12+\n" +
	"\x11uptime_percentage\x18\x05 \x01(\x01R\x10uptimePercentage\x12/\n" +
	"\x14avg_response_time_ms\x18\x06 \x01(\x01R\x11avgResponseTimeMs\x12(\n" +
	"\x10last_status_code\x18\a \x01(\x05R\x0elastStatusCode\x12&\n" +
	"\x0fis_currently_up\x18\b \x01(\bR\risCurrentlyUp\"2\n" +
	"\x17GetUserDashboardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xf4\x01\n" +
	"\rUserDashboard\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"total_urls\x18\x02 \x01(\x05R\ttotalUrls\x12\x1f\n" +
	"\vactive_urls\x18\x03 \x01(\x05R\n" +
	"activeUrls\x12*\n" +
	"\x11urls_currently_up\x18\x04 \x01(\x05R\x0furlsCurrentlyUp\x12.\n" +
	"\x13urls_currently_down\x18\x05 \x01(\x05R\x11urlsCurrentlyDown\x12.\n" +
	"\btop_urls\x18\x06 \x03(\v2\x13.analytics.URLStatsR\atopUrls2\xa7\x01\n" +
	"\x10AnalyticsService\x12A\n" +
	"\vGetURLStats\x12\x1d.analytics.GetURLStatsRequest\x1a\x13.analytics.URLStats\x12P\n" +
	"\x10GetUserDashboard\x12\".analytics.GetUserDashboardRequest\x1a\x18.analytics.UserDashboardB;Z9github.com/shakir/url-monitor/proto/analytics;analyticspbb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*GetURLStatsRequest)(nil),      // 0: analytics.GetURLStatsRequest
	(*URLStats)(nil),                // 1: analytics.URLStats
	(*GetUserDashboardRequest)(nil), // 2: analytics.GetUserDashboardRequest
	(*UserDashboard)(nil),           // 3: analytics.UserDashboard
	(*timestamp.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	4, // 0: analytics.GetURLStatsRequest.from:type_name -> google.protobuf.Timestamp
	4, // 1: analytics.GetURLStatsRequest.to:type_name -> google.protobuf.Timestamp
	1, // 2: analytics.UserDashboard.top_urls:type_name -> analytics.URLStats
	0, // 3: analytics.AnalyticsService.GetURLStats:input_type -> analytics.GetURLStatsRequest
	2, // 4: analytics.AnalyticsService.GetUserDashboard:input_type -> analytics.GetUserDashboardRequest
	1, // 5: analytics.AnalyticsService.GetURLStats:output_type -> analytics.URLStats
	3, // 6: analytics.AnalyticsService.GetUserDashboard:output_type -> analytics.UserDashboard
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
